"""Generates the guns' Minecraft assets: 16x16 pixel-art sprites (original art, drawn here), item definitions,
models and names. Run: python tools/gen_guns.py  (from mc/; needs Pillow). Barrels point right; the hand
transforms are the crossbow's turned 135 degrees in the sprite's plane, so they aim the way a crossbow does."""
import json, pathlib
from PIL import Image

OUT = pathlib.Path(__file__).resolve().parent.parent / "src/main/resources/assets/passthrough"
PALETTE = {
    "K": (24, 24, 28), "D": (52, 55, 62), "M": (90, 95, 106), "L": (150, 157, 170), "W": (88, 56, 30),
    "B": (139, 92, 50), "b": (171, 120, 70), "O": (88, 101, 55), "o": (62, 72, 38), "R": (176, 42, 32),
    "r": (214, 84, 52), "Y": (110, 196, 228), "G": (196, 162, 64),
}
SPRITES = {
    "pistol": """
................
................
................
................
................
...KKKKKKKKKKK..
...KLLLLLLLLLMK.
...KMMMMMMMMMMK.
...KKDDKKKKKKKK.
....KDDKDK......
....KDDKK.......
...KDDDK........
...KDDDK........
...KKKKK........
................
................""",
    "smg": """
................
................
................
.....K..........
....KKKKKKKKKK..
.KKKKMMMMMMMMLKK
KDDKMMMMMMMMMMMK
KDDDKKKDDKKKMMKK
.KKKK.KDDK.KDK..
......KDK..KDK..
.....KDDK..KDK..
.....KKKK..KDK..
...........KKK..
................
................
................""",
    "assault_rifle": """
................
................
................
................
.....KK.........
....KMMKKKKKK...
KKKKMMMMMMMMMKKK
KBBKMMMMMMMMMMMK
KBbBKKDDKKOOKKKK
KBBBK.KDDKOoK...
.KKKK.KDDKOoK...
......KDDKOoK...
......KKKKKKK...
................
................
................""",
    "pump_shotgun": """
................
................
................
................
................
................
KKKK.KKKKKKKKKKK
KbBBKKMMMMMMMMLK
KBBBBKDDDDDDDDDK
.KBBBKKKBbbBBKKK
..KKKK.KBBBBK...
....KDK.KKKK....
....KKK.........
................
................
................""",
    "sniper_rifle": """
................
................
................
.....KKKKKK.....
....KYDDDDLK....
.....KKKKKK.....
......K..K......
KKKKKKKKKKKKKKKK
KBBBBBMMMMMMMMLK
KBbBBBBKKKKKKKKK
.KKBBKDK........
...KKKDK........
.....KKK........
................
................
................""",
    "rpg": """
................
................
................
............KK..
....KKKKKKKKrRK.
KKKKOOOOOOOOrRRK
KDDKOOOOOOOOrRRK
KKKKoooooooorRK.
....KKKKDDKKKK..
.......KDK......
.......KDK......
.......KKK......
................
................
................
................""",
}
NAMES = {"pistol": "Pistol", "smg": "SMG", "assault_rifle": "Assault Rifle", "pump_shotgun": "Pump Shotgun",
         "sniper_rifle": "Sniper Rifle", "rpg": "RPG"}
TURN = 135  # crossbow sprite faces top-left; these face right
DISPLAY = {
    "thirdperson_righthand": {"rotation": [-90, 0, -60 + TURN], "translation": [2, 0.1, -3], "scale": [0.9, 0.9, 0.9]},
    "thirdperson_lefthand": {"rotation": [-90, 0, 30 + TURN], "translation": [2, 0.1, -3], "scale": [0.9, 0.9, 0.9]},
    "firstperson_righthand": {"rotation": [-90, 0, -55 + TURN], "translation": [1.13, 3.2, 1.13], "scale": [0.55, 0.55, 0.55]},
    "firstperson_lefthand": {"rotation": [-90, 0, 35 + TURN], "translation": [1.13, 3.2, 1.13], "scale": [0.55, 0.55, 0.55]},
}


def main():
    for d in ("items", "models/item", "textures/item", "lang"):
        (OUT / d).mkdir(parents=True, exist_ok=True)
    for name, art in SPRITES.items():
        rows = [r for r in art.strip("\n").split("\n")]
        assert len(rows) == 16 and all(len(r) == 16 for r in rows), (name, [len(r) for r in rows])
        img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
        for y, row in enumerate(rows):
            for x, ch in enumerate(row):
                if ch != ".":
                    img.putpixel((x, y), PALETTE[ch] + (255,))
        img.save(OUT / f"textures/item/{name}.png")
        (OUT / f"items/{name}.json").write_text(json.dumps(
            {"model": {"type": "minecraft:model", "model": f"passthrough:item/{name}"}}, indent=2))
        (OUT / f"models/item/{name}.json").write_text(json.dumps(
            {"parent": "minecraft:item/generated", "textures": {"layer0": f"passthrough:item/{name}"}, "display": DISPLAY}, indent=2))
    (OUT / "lang/en_us.json").write_text(json.dumps({f"item.passthrough.{k}": v for k, v in NAMES.items()}, indent=2))
    print("wrote", len(SPRITES), "guns to", OUT)


main()
